# Site Info
title: Kris M. Reid
tagline: 'The home of Kris M. Reid'
description: 'A website featuring the CV and creative database for Kristopher Reid'
baseurl: "/lanyon"
url: http://codinfox.github.io
logo: ''

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Kris Reid
  description: A passionate strategic marketing communication professional, learning to be greater than great.
  gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/kristopher-reid-1186326a
    github:    https://github.com/krismreid
    # facebook:  <hide>
    # twitter:   <hide>
    wordpress: krismreid.wordpress.com
    email:     kristophermarkellreid@gmail.com
    
# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Resume:
    - '/resume/'
  Creative Database: 
    - '/creative database/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="https://krismreid.files.wordpress.com/2016/09/cropped-img_0071.jpg">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax


